### ISSUE TITLE
Replace old logo with new one in blog

### ISSUE THREAD

**Issue by aanthonymax** [hmpl-language/hmpl#10]
Needs [blog](https://github.com/hmpl-language/hmpl/tree/main/www/blog) to replace the logo in the footer with a new one 

![Screenshot 2024-11-15 at 20 10 08](https://github.com/user-attachments/assets/6c1f59ab-9caf-4afa-83bb-10f59556bccc)

**Comment by joharkhan99** [comment]
👋Hey @aanthonymax, I would like to work on this issue. If no one else is working on it, please assign it to me. Thanks.

**Comment by aanthonymax** [comment]
@joharkhan99 Thank you very much! Yes, if you have time, you can!

**Comment by aanthonymax** [comment]
@joharkhan99 `bundle exec jekyll serve` - this command is used to run the bundle

**Comment by joharkhan99** [comment]
Thank you, @aanthonymax. I have a quick question: Should I replace the Twitter logo and add the logo of HMPL?

**Comment by aanthonymax** [comment]
@joharkhan99 Need to change old twitter logo to new one. Previously there was a bird, now there is X.

```html
<svg width="35" height="32" viewBox="0 0 35 32" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M26.897 0H32.3288L20.4026 13.5793L34.3362 32H23.4018L14.841 20.8059L5.04022 32H-0.391519L12.2432 17.476L-1.10001 0H10.1059L17.8402 10.2258L26.897 0ZM24.9959 28.8118H28.007L8.52361 3.07011H5.28819L24.9959 28.8118Z" fill="000"></path> </svg>
```

**Comment by aanthonymax** [comment]
@joharkhan99 I took this svg from [hmpl-lang.dev](hmpl-lang.dev) in the header. You can take it from there.

**Comment by joharkhan99** [comment]
Alright and should I add the HMPL logo to the footer as well? or is it fine the way it is right now

**Comment by aanthonymax** [comment]
@joharkhan99 Everything is fine. Needs to replace the Twitter logo only.

**Comment by aanthonymax** [comment]
@joharkhan99 https://blog.hmpl-lang.dev - All fine. Thanks!
