### ISSUE TITLE
The blog needs to have breadcrumbs or a back button added for article.

### ISSUE THREAD

**Issue by aanthonymax** [hmpl-language/hmpl#21]
When going to an article there is no back button or at least breadcrumbs. It is necessary to add such functionality so that it would be possible to navigate through the pages normally.

![Screenshot 2024-11-24 at 00 16 23](https://github.com/user-attachments/assets/daad194e-5d51-4356-be7a-cb6b2c43b025)

Site - [https://blog.hmpl-lang.dev](https://blog.hmpl-lang.dev)
Blog files - [https://github.com/hmpl-language/hmpl/tree/main/www/blog](https://github.com/hmpl-language/hmpl/tree/main/www/blog)

**Comment by ibrahim-gabr** [comment]
👋Hey @aanthonymax, I would like to work on this issue. If no one else is working on it, please assign it to me. Thanks.

**Comment by aanthonymax** [comment]
@ibrahim-gabr Thank you very much! It would be great if you have time for this issue!

**Comment by aanthonymax** [comment]
The site is on jekyll, located right in this repository in the `www` folder. From there it is deployed directly to the server - you can see it at the link - https://blog.hmpl-lang.dev

**Comment by aanthonymax** [comment]
@ibrahim-gabr Thank you! Everything is cool

**Comment by ibrahim-gabr** [comment]
Many thanks @aanthonymax
