### ISSUE TITLE
It is necessary to write small comments for each block of code in the main.js file about what it does.

### ISSUE THREAD

**Issue by aanthonymax** [hmpl-language/hmpl#7]
It is necessary to go through the code in [main.js](https://github.com/hmpl-language/hmpl/blob/main/src/main.ts) and make small comments on what the function does in a nutshell. Take an example of the comment format from [types.ts](https://github.com/hmpl-language/hmpl/blob/main/src/types.ts). 

The type itself looks like this:

```typescript
/**
 * Outputs a message to the console
 */

console.log("123");
```

**Comment by svetozar12** [comment]
Hello I would be happy to help with this issue.

**Comment by aanthonymax** [comment]
@svetozar12 Hello! Thank you very much! Yes, it would be great if you could help.

**Comment by aanthonymax** [comment]
@svetozar12 Thank you very much! Everything is great!
